service: default
runtime: nodejs16
env: standard
instance_class: F4_1G
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
automatic_scaling:
  target_cpu_utilization: 0.75
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80